name: Read Secret
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      MYPASSWORD: ${{ secrets.MYPASSWORD }}
    steps:
      - run: echo "${MYPASSWORD}"
      - run: echo "${MYPASSWORD:0:1} ${MYPASSWORD#?}"
